# Generated by Django 4.2.6 on 2023-10-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210411_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.IntegerField(choices=[('0', 'Male'), ('1', 'Female')], default=1),
        ),
    ]
