# Generated by Django 4.2.6 on 2023-10-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_staff_image'),
        ('core', '0018_alter_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.staff'),
        ),
    ]
