# Generated by Django 4.2.6 on 2023-10-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_staff_image'),
        ('core', '0020_appointment_status_alter_appointment_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
    ]
