# Generated by Django 4.2.6 on 2023-10-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_bookingslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='your_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bookingslot'),
        ),
    ]
