# Generated by Django 4.2.6 on 2023-10-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_timeslot_appointment_your_date_appointment_your_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
