# Generated by Django 4.2.6 on 2023-11-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_chatmessage_alter_appointment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='your_time',
            field=models.TimeField(),
        ),
    ]
